name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint-and-build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Ajouter la clé SSH privée
      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Étape 3 : Configurer Node.js avec le cache
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      # Étape 4 : Installer les dépendances
      - name: Install dependencies
        run: npm install

      # Étape 5 : Vérifier le formatage avec Prettier
      - name: Run Prettier
        run: npm run format

      # Étape 6 : Lancer ESLint
      - name: Run ESLint
        run: npm run lint

      # Étape 7 : Vérifier les types avec TypeScript
      - name: TypeScript Type Check
        run: npm run type-check

      # Étape 8 : Construire le projet
      - name: Build Project
        run: npm run build
